# Generated by Django 6.0.3 on 2026-04-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0002_mediaassets_delete_mediaasset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaassets',
            options={'ordering': ['-id']},
        ),
    ]
